var names = {
    "1": "Who",
    "2": "Onward to the Promised Resort! Vegeta Goes on a Family Trip?!",
    "3": "Where Does the Dream Continue?! Find Super Saiyan God!",
    "4": "Aim for the Dragon Balls! The Pilaf Gang’s Great Strategy!",
    "5": "Showdown on Kaiō’s Planet! Goku vs God of Destruction Beerus",
    "6": "Don’t Anger the God of Destruction! The Heart Pounding Birthday Party",
    "7": "How Dare You Hit My Bulma! Vegeta’s Furious Mutation?!",
    "8": "Goku Steps Up! The Last Chance From Beerus-sama?!",
    "9": "Sorry About the Wait, Beerus Finally, Super Saiyan God is",
    "10": "Show",
    "11": "Let’s Keep Going Beerus-sama! The Battle of Gods Continues!",
    "12": "The Universe Crumbles?! Clash! The God of Destruction vs Super Saiyan",
    "13": "Goku,",
    "14": "This is Every Last Bit of My Power! The Battle of Gods Concludes!",
    "15": "Heroic Satan, Cause a Miracle! A Challenge From Outer Space!!",
    "16": "Vegeta Becomes a Pupil?! Take Down Whis!",
    "17": "Pan",
    "18": "I’ve Come Too! Training Begins on Beerus’ Planet!",
    "19": "Despair Once More! Revival of the Evil Emperor, Freeza!",
    "20": "A Warning From Jaco! Freeza and 1,000 Soldiers are Fast Approaching!",
    "21": "The Revenge Begins! The Freeza Army’s Malice Strikes Gohan!",
    "22": "Change! An Impossible Revival! The Name’s Ginyu!!",
    "23": "The Earth and Gohan in Dire Peril! Come Quick, Son Goku!!",
    "24": "Clash: Freeza vs Son Goku! This is the Fruit of My Training!",
    "25": "An",
    "26": "Amidst the Crisis, a Shot at Victory Appears! Son Goku’s Counterattack",
    "27": "The Earth",
    "28": "The",
    "29": "It’s Settled: We’re Holding a Martial Arts Match!The Team Captain’s Even",
    "30": "Rehearsing for the “Martial Arts Match” — Who Are the Two Remaining",
    "31": "To Lord Zuno! Ask About the Location of the Super Dragon Balls!",
    "32": "The Matches Begin! Everyone Head to the “Nameless Planet”!",
    "33": "Be Surprised, Universe 6! This is Super Saiyan Son Goku!",
    "34": "Piccolo vs Frost — Bet Everything on the Makankōsappō!",
    "35": "Turn Anger Into Power! Vegeta’s All-Out Battle",
    "36": "An Unexpectedly Tough Fight! Vegeta’s Explosion of Rage!",
    "37": "Don’t Forget Your Saiyan Pride! Vegeta vs the Saiyan of Universe",
    "38": "Universe 6’s Strongest Warrior! Meet the Assassin Hit!!",
    "39": "A Fully-Developed “Time-Skip” Counterattack?! Is It Coming?! Goku’s New",
    "40": "The Conclusion At Last! Who Will Prevail? Beerus, or Champa?",
    "41": "Come Forth, Dragon of the Gods — Grant My Wish, Pretty Peas!",
    "42": "A Tumultuous Victory Celebration! Facing Off At Last: Monaka vs Son Goku?!",
    "43": "Goku’s “Ki” is Out of Control?! Lots of Trouble Taking Care of Pan",
    "44": "The Seal of Planet Potaufeu — Secret of the Unleashed “Superhuman Water”!",
    "45": "Vegeta",
    "46": "Goku vs Copy-Vegeta! Who Will Prevail?!",
    "47": "SOS From the Future! A Black New Enemy Appears!!",
    "48": "Hope",
    "49": "A",
    "50": "Goku vs Black! The Path to the Sealed Future",
    "51": "Feelings That",
    "52": "Master and Pupil Reunion — Son Gohan and “Future” Trunks",
    "53": "Reveal Black’s True Identity! Now, to the Kaiōshin Realm of Universe 10!",
    "54": "Inheritor of Saiyan Blood — Trunks’ Resolve",
    "55": "Hey, I Wanna Meet Son Goku — A Summons from the Omni-King!",
    "56": "Rematch With Goku Black! Introducing Super Saiyan Rosé",
    "57": "Advent of",
    "58": "Zamasu and",
    "59": "Protect Kaiōshin Gowasu — Destroy Zamasu!",
    "60": "Back to the Future — Goku Black’s Identity Revealed!!",
    "61": "Zamasu’s Ambition — Presenting the Terrifying “0 Mortals Plan”",
    "62": "I’ll Protect the World! Trunks’ Angry Super Power Explosion!!",
    "63": "Don’t Defile Saiyan Cells! The Curtain Rises on Vegeta’s Intense Battle!!",
    "64": "Praise",
    "65": "Final Judgement?! The Supreme God’s Ultimate Power",
    "66": "Showdown! The Unyielding Warriors’ Miraculous Super Power",
    "67": "Fill",
    "68": "Come Forth, Shenlong! Whose Wish Shall Be Granted?!",
    "69": "Goku vs Arale! Earth Ends in a Wacky Battle?!",
    "70": "Champa’s Challenge! This Time Let’s Face Off in Baseball!!",
    "71": "Goku Dies! A",
    "72": "Can You",
    "73": "Gohan’s Disaster! Great Saiyaman’s Unbelievable Movie Adaptation?!",
    "74": "For The Sake of Those He Loves! The Indomitable Great Saiyaman!!",
    "75": "Goku",
    "76": "Beat the Fearsome Foes! Kuririn’s Fighting Spirit Returns!",
    "77": "Let’s Do It,",
    "78": "The Universes’ Gods are Aghast! Losers Will Be Obliterated at the",
    "79": "Universe 9’s Kicker Basil vs Universe 7’s Majin Boo!!",
    "80": "Awaken Dormant Fighting Spirit! Son Gohan’s Battle!!",
    "81": "Crusher Bergamo vs Son Goku! Who Has Sky-High Power?!",
    "82": "Never Forgive Son Goku! The Warrior of Justice Toppo Intrudes!!",
    "83": "Form the Universe 7 Team! Who Are the Strongest Ten?!",
    "84": "Son Goku the Talent Scout — Inviting Kuririn and No. 18",
    "85": "The Universes Get",
    "86": "Trading Blows for the First Time! Artificial Human No. 17 vs Son Goku!!",
    "87": "Hunt the Poachers! Goku and No. 17’s Joint Battle!!",
    "88": "Gohan and Piccolo: Master and Disciple Train to the Limit!",
    "89": "A",
    "90": "Facing",
    "91": "Which Universe Will Prevail?! The Mightiest Warriors",
    "92": "An Emergency Development! We Don’t Have Ten Members!!",
    "93": "You’re the Tenth Warrior! Goku Visits Freeza!!",
    "94": "Revival of the Evil Emperor! The Mysterious Awaiting Assassins?!",
    "95": "The Wickedest! The",
    "96": "The Time Has Come! To the World of Void, Where the Universes’ Fate Will Be",
    "97": "Survive! The “Tournament of Power” Begins at Last!!",
    "98": "Oh, the Uncertainty! The",
    "99": "Show It Off!",
    "100": "Rampage! The",
    "101": "The",
    "102": "The Power of Love Explodes?! Universe 2’s Magical Girl Warriors!!",
    "103": "Gohan, Be Ruthless! The Showdown with Universe 10!!",
    "104": "A Faster-Than-Light Battle Begins! Goku and Hit’s Joint Front!!",
    "105": "A Fierce Battle!",
    "106": "Figure It Out! Death Match Against an Unseen Attacker!!",
    "107": "Revenge “F”! A Cunning Trap is Set?!",
    "108": "Freeza and",
    "109": "The Ultimate Enemy Approaches Goku! Now, Let Loose! The Killer",
    "110": "Son Goku Wakes! New Level of the Awakened!!",
    "111": "Extreme Battle of Another Dimension! Hit vs Jiren!!",
    "112": "A Saiyan’s",
    "113": "With Such Joy! The Fighting-Maniac Saiyans Battle Again!!",
    "114": "Ghastly! The Explosive Birth of a New Super Warrior!!",
    "115": "Goku vs Kafla! Super Saiyan Blue Defeated?!",
    "116": "The Comeback Omen! Ultra Instinct’s Great Explosion!!",
    "117": "A Grand Showdown of Love! The Artificial Humans vs Universe 2!!",
    "118": "Accelerating Drama:",
    "119": "Unavoidable?!",
    "120": "A Perfect Survival Strategy! Universe 3’s Menacing Assassins!!",
    "121": "All-Out War! The Ultimate 4-Way Combo vs Universe 7’s Total Offensive!!",
    "122": "Staking His Pride! Vegeta Challenges the Strongest!!",
    "123": "Full Body, Spirit, and Power Unleashed! Goku and Vegeta!!",
    "124": "A Stormy,",
    "125": "Majestic! Advent of",
    "126": "Surpass Even a God! Vegeta’s Life-Risking Blow!!",
    "127": "A Looming Obstacle! Pinning Hope on a Final Barrier!!",
    "128": "With",
    "129": "Transcendent Limits Surpassed! Ultra Instinct Mastered!!",
    "130": "An Unprecedented Super Showdown! The Ultimate Survival Battle!!",
    "131": "A Miraculous Conclusion! Farewell Goku! Until the Day We Meet Again!!"
}